# https://spring.pleiades.io/spring-boot/appendix/application-properties/

spring:
  application:
    name: order-mnt1

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  jpa:
    open-in-view: false
    hibernate:
      # 組み込みデータベースを使用し、スキーママネージャーが検出されなかった場合、デフォルトは "create-drop" ってことに注意。
      ddl-auto: none

  thymeleaf:
    cache: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
