spring:
  application:
    name: order-mnt1

  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password: password

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  thymeleaf:
    cache: false

  sql:
    init:
      mode: always
