spring:
  application:
    name: order-mnt1

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  thymeleaf:
    cache: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
