-- 初期データ投入用のSQL

-- ESTIMATEテーブルにダミーデータを挿入
INSERT INTO ESTIMATE (ESTIMATE_ID, EMPLOYEE_CODE, ORDER_STATUS, ORDER_PROBABILITY, ESTIMATE_DATE, COMPANY_NAME, COMPANY_NAME_KANA, CLIENT_CONTACT, CLIENT_CONTACT_KANA, CLIENT_ORDER_NUMBER, SUBJECT, DELIVERY_DATE, INSPECTION_DATE, PAYMENT_TERMS, TOTAL_AMOUNT, ESTIMATE_AMOUNT, NOTES, IS_LATEST, IS_DELETED)
VALUES ('DUMMY001', 'EMP001', 'Pending', 'High', '2025-05-23', 'ダミー株式会社', 'ダミーカブシキガイシャ', '山田太郎', 'ヤマダタロウ', 'CUST001', 'ダミー案件', '2025-06-01', '2025-06-15', '現金払い', 100000.00, 95000.00, '特記事項なし', TRUE, FALSE);
