-- テーブル作成用のDDL

-- ESTIMATE Table
CREATE TABLE IF NOT EXISTS ESTIMATE (
    ESTIMATE_ID VARCHAR(50) PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(50),
    ORDER_STATUS VARCHAR(50),
    ORDER_PROBABILITY VARCHAR(50),
    ESTIMATE_DATE DATE,
    COMPANY_NAME VARCHAR(100),
    COMPANY_NAME_KANA VARCHAR(100),
    CLIENT_CONTACT VARCHAR(100),
    CLIENT_CONTACT_KANA VARCHAR(100),
    CLIENT_ORDER_NUMBER VARCHAR(50),
    SUBJECT VARCHAR(200),
    DELIVERY_DATE DATE,
    INSPECTION_DATE DATE,
    PAYMENT_TERMS VARCHAR(100),
    TOTAL_AMOUNT DECIMAL(15, 2),
    ESTIMATE_AMOUNT DECIMAL(15, 2),
    NOTES VARCHAR(500),
    IS_LATEST BOOLEAN,
    IS_DELETED BOOLEAN
);

-- ESTIMATE_DETAIL Table
CREATE TABLE IF NOT EXISTS ESTIMATE_DETAIL (
    ESTIMATE_ID VARCHAR(50),
    DETAIL_ID INT,
    ITEM VARCHAR(100),
    DETAIL VARCHAR(200),
    REMARKS VARCHAR(200),
    QUANTITY INT,
    UNIT VARCHAR(50),
    UNIT_PRICE DECIMAL(15, 2),
    AMOUNT DECIMAL(15, 2),
    IS_LATEST BOOLEAN,
    IS_DELETED BOOLEAN,
    PRIMARY KEY (ESTIMATE_ID, DETAIL_ID),
    FOREIGN KEY (ESTIMATE_ID) REFERENCES ESTIMATE(ESTIMATE_ID)
);

-- ORDER Table
CREATE TABLE IF NOT EXISTS ORDER_TABLE (
    ORDER_ID VARCHAR(50) PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(50),
    ESTIMATE_ID VARCHAR(50),
    ORDER_DATE DATE,
    COMPANY_NAME VARCHAR(100),
    COMPANY_NAME_KANA VARCHAR(100),
    CLIENT_CONTACT VARCHAR(100),
    CLIENT_CONTACT_KANA VARCHAR(100),
    CLIENT_ORDER_NUMBER VARCHAR(50),
    SUBJECT VARCHAR(200),
    DELIVERY_DATE DATE,
    INSPECTION_DATE DATE,
    PAYMENT_TERMS VARCHAR(100),
    TOTAL_AMOUNT DECIMAL(15, 2),
    NOTES VARCHAR(500),
    IS_LATEST BOOLEAN,
    IS_DELETED BOOLEAN,
    FOREIGN KEY (ESTIMATE_ID) REFERENCES ESTIMATE(ESTIMATE_ID)
);

-- ORDER_DETAIL Table
CREATE TABLE IF NOT EXISTS ORDER_DETAIL (
    ORDER_ID VARCHAR(50),
    DETAIL_ID INT,
    REMARKS VARCHAR(200),
    QUANTITY INT,
    UNIT VARCHAR(50),
    UNIT_PRICE DECIMAL(15, 2),
    AMOUNT DECIMAL(15, 2),
    IS_LATEST BOOLEAN,
    IS_DELETED BOOLEAN,
    PRIMARY KEY (ORDER_ID, DETAIL_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(ORDER_ID)
);

-- INVOICE Table
CREATE TABLE IF NOT EXISTS INVOICE (
    INVOICE_ID VARCHAR(50) PRIMARY KEY,
    ORDER_ID VARCHAR(50),
    EMPLOYEE_CODE VARCHAR(50),
    INVOICE_DATE DATE,
    COMPANY_NAME VARCHAR(100),
    COMPANY_NAME_KANA VARCHAR(100),
    CLIENT_CONTACT VARCHAR(100),
    CLIENT_CONTACT_KANA VARCHAR(100),
    CLIENT_ORDER_NUMBER VARCHAR(50),
    SUBJECT VARCHAR(200),
    DELIVERY_DATE DATE,
    PAYMENT_TERMS VARCHAR(100),
    TOTAL_AMOUNT DECIMAL(15, 2),
    TAX_CATEGORY VARCHAR(50),
    TAX_RATE DECIMAL(5, 2),
    TAX_AMOUNT DECIMAL(15, 2),
    INVOICE_AMOUNT DECIMAL(15, 2),
    NOTES VARCHAR(500),
    IS_LATEST BOOLEAN,
    IS_DISCARDED BOOLEAN,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_TABLE(ORDER_ID)
);

-- INVOICE_DETAIL Table
CREATE TABLE IF NOT EXISTS INVOICE_DETAIL (
    INVOICE_ID VARCHAR(50),
    DETAIL_ID INT,
    ITEM VARCHAR(100),
    DETAIL VARCHAR(200),
    REMARKS VARCHAR(200),
    QUANTITY INT,
    UNIT VARCHAR(50),
    UNIT_PRICE DECIMAL(15, 2),
    AMOUNT DECIMAL(15, 2),
    IS_LATEST BOOLEAN,
    IS_DISCARDED BOOLEAN,
    PRIMARY KEY (INVOICE_ID, DETAIL_ID),
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID)
);
